name: idiomasapp
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  lottie: ^3.1.2
  cupertino_icons: ^1.0.8
  speech_to_text: 7.3.0
  http: ^1.2.1
  http_parser: ^4.0.0
  path_provider: ^2.1.3
  flutter_sound: ^9.3.0
  permission_handler: ^11.3.1
  flutter_tts: ^4.0.2
  web_socket_channel: ^2.2.0
  intl: ^0.19.0
  image_picker: ^0.8.7+4
  google_mlkit_text_recognition: ^0.15.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/oso_polar.json
    - assets/anim_correct.json
    - assets/anim_wrong.json

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/app_icon.png
